version: "3.7"
services:
  db:
    build: "./backend/db"
    image: db-gconta-image
    restart: always
    container_name: db-gconta-container
    env_file:
      - ./backend/db/db.env
    networks:
      - gconta-network
    volumes:
      - ./backend/db/data:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  backend:
    build: "./backend"
    restart: always
    image: api-gconta-image
    container_name: api-gconta-container
    env_file:
      - ./backend/.env.prod    
    volumes:
      - ./backend:/home/node/app
      - ./backend/uploads/logos:/dist/uploads/logos
    ports:
      - "3002:3000"
    depends_on:
      - db
    networks:
      - gconta-network

  frontend:
    build: "./frontend-vite"
    container_name: frontend-gconta-container
    image: front-gconta-image
    env_file:
      - ./frontend-vite/.env.prod       
    restart: always
    volumes:
      - ./frontend-vite/nginx/nginx.config:/etc/nginx/conf.d/default.conf    
    ports:
      - "82:80"
    environment:
      - NGINX_HOST=gconta.com
      - NGINX_PORT=82
    depends_on:
      - db
      - backend
    networks:
      - gconta-network
networks:
  gconta-network:
