FROM node:21-alpine AS build-stage

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx AS production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY ./nginx/nginx.config /etc/nginx/conf.d/default.conf


